import type { PayerItem } from './payerTargetTypes'

export const initialPayerItems: PayerItem[] = [
  {
    id: 1,
    historyId: 1,
    name: '김하늘',
    affiliation: '센트레빌 입주자대표회의',
    amountValue: 1250000,
    noticeGeneratedAt: '2026-03-13',
    advanceDueDate: '2026-04-30',
    confirmedDueDate: null,
    dueDate: '2026-04-30',
    paymentCompletedAt: null,
    paymentStatus: 'unpaid',
    status: 'advance',
    violation: {
      occurredAt: '2026-03-12 08:25',
      location: '부산 해운대구 센텀중앙로 45 앞',
      vehicleNumber: '12가 3456',
      email: 'haneul.kim@example.com',
      address: '부산 해운대구 센텀중앙로 101 센트레빌 102동 1203호',
      detail: '지정 주차구역 외 구역에 장시간 주차되어 사전납부 대상자로 분류되었습니다.',
    },
    documents: [
      {
        id: 'pre-notice',
        title: '사전통지서',
        fileName: '행정처분(과태료) 사전통지서_김하늘.pdf',
        filePath: 'C:\\notice-generator\\samples\\pre_notice_kim_haneul.pdf',
      },
      {
        id: 'suspension',
        title: '운전업무정지',
        fileName: '행정처분(운전업무정지) 사전통지서_김하늘.pdf',
        filePath: 'C:\\notice-generator\\samples\\suspension_notice_kim_haneul.pdf',
      },
      {
        id: 'final-notice',
        title: '확정통지서',
        fileName: '행정처분 확정통지서_김하늘.pdf',
        filePath: null,
      },
    ],
  },
  {
    id: 2,
    historyId: 2,
    name: '이서준',
    affiliation: '센트레빌 관리사무소',
    amountValue: 980000,
    noticeGeneratedAt: '2026-03-11',
    advanceDueDate: '2026-04-30',
    confirmedDueDate: '2026-04-30',
    dueDate: '2026-04-30',
    paymentCompletedAt: '2026-03-18',
    paymentStatus: 'paid',
    status: 'confirmed',
    violation: {
      occurredAt: '2026-03-10 21:15',
      location: '부산 수영구 광안로 118 지하주차장',
      vehicleNumber: '34나 7821',
      email: 'seojun.lee@example.com',
      address: '부산 수영구 광안해변로 220 광안대교 203동 904호',
      detail: '반복 위반 건으로 확인되어 확정통지서 발송 및 납부 완료 처리까지 완료되었습니다.',
    },
    documents: [
      {
        id: 'pre-notice',
        title: '사전통지서',
        fileName: '행정처분(과태료) 사전통지서_이서준.pdf',
        filePath: 'C:\\notice-generator\\samples\\pre_notice_lee_seojun.pdf',
      },
      {
        id: 'suspension',
        title: '운전업무정지',
        fileName: '행정처분(운전업무정지) 사전통지서_이서준.pdf',
        filePath: 'C:\\notice-generator\\samples\\suspension_notice_lee_seojun.pdf',
      },
      {
        id: 'final-notice',
        title: '확정통지서',
        fileName: '행정처분 확정통지서_이서준.pdf',
        filePath: 'C:\\notice-generator\\samples\\final_notice_lee_seojun.pdf',
      },
    ],
  },
  {
    id: 3,
    historyId: 3,
    name: '정유진',
    affiliation: '리버뷰 비상대책위원회',
    amountValue: 1430000,
    noticeGeneratedAt: '2026-03-09',
    advanceDueDate: '2026-04-30',
    confirmedDueDate: null,
    dueDate: '2026-04-30',
    paymentCompletedAt: '2026-03-17',
    paymentStatus: 'paid',
    status: 'advance',
    violation: {
      occurredAt: '2026-03-08 07:40',
      location: '부산 북구 금곡대로 211 상가 앞',
      vehicleNumber: '89다 1104',
      email: 'yujin.jung@example.com',
      address: '부산 북구 화명신도시로 55 리버뷰 305동 1502호',
      detail: '야간 시간대 반복 진출입 내역과 속도 위반 기록이 확인되어 통지서가 생성되었습니다.',
    },
    documents: [
      {
        id: 'pre-notice',
        title: '사전통지서',
        fileName: '행정처분(과태료) 사전통지서_정유진.pdf',
        filePath: 'C:\\notice-generator\\samples\\pre_notice_jung_yujin.pdf',
      },
      {
        id: 'suspension',
        title: '운전업무정지',
        fileName: '행정처분(운전업무정지) 사전통지서_정유진.pdf',
        filePath: 'C:\\notice-generator\\samples\\suspension_notice_jung_yujin.pdf',
      },
      {
        id: 'final-notice',
        title: '확정통지서',
        fileName: '행정처분 확정통지서_정유진.pdf',
        filePath: null,
      },
    ],
  },
  {
    id: 4,
    historyId: 4,
    name: '한도윤',
    affiliation: '리버뷰 입주자대표회의',
    amountValue: 1110000,
    noticeGeneratedAt: '2026-03-15',
    advanceDueDate: '2026-04-30',
    confirmedDueDate: '2026-04-30',
    dueDate: '2026-04-30',
    paymentCompletedAt: null,
    paymentStatus: 'unpaid',
    status: 'confirmed',
    violation: {
      occurredAt: '2026-03-14 13:05',
      location: '부산 남구 동호로 77 진입램프',
      vehicleNumber: '45라 6678',
      email: 'doyun.han@example.com',
      address: '부산 남구 동호로 77 리버뷰 101동 802호',
      detail: '과태료 및 정지 처분 동시 대상 건으로 확인되어 확정 납부 대상자로 전환되었습니다.',
    },
    documents: [
      {
        id: 'pre-notice',
        title: '사전통지서',
        fileName: '행정처분(과태료) 사전통지서_한도윤.pdf',
        filePath: 'C:\\notice-generator\\samples\\pre_notice_han_doyun.pdf',
      },
      {
        id: 'suspension',
        title: '운전업무정지',
        fileName: '행정처분(운전업무정지) 사전통지서_한도윤.pdf',
        filePath: 'C:\\notice-generator\\samples\\suspension_notice_han_doyun.pdf',
      },
      {
        id: 'final-notice',
        title: '확정통지서',
        fileName: '행정처분 확정통지서_한도윤.pdf',
        filePath: 'C:\\notice-generator\\samples\\final_notice_han_doyun.pdf',
      },
    ],
  },
  {
    id: 5,
    historyId: 5,
    name: '오지안',
    affiliation: '메이플파크 교통대책위원회',
    amountValue: 890000,
    noticeGeneratedAt: '2026-03-12',
    advanceDueDate: '2026-04-30',
    confirmedDueDate: null,
    dueDate: '2026-04-30',
    paymentCompletedAt: '2026-03-19',
    paymentStatus: 'paid',
    status: 'advance',
    violation: {
      occurredAt: '2026-03-11 18:10',
      location: '부산 동래구 충렬대로 51 교차로',
      vehicleNumber: '67마 9201',
      email: 'jian.oh@example.com',
      address: '부산 동래구 중앙대로 88 메이플파크상가 402호',
      detail: '단속 장비 기록과 현장 확인 내역이 일치하여 사전통지 대상자로 등록되었습니다.',
    },
    documents: [
      {
        id: 'pre-notice',
        title: '사전통지서',
        fileName: '행정처분(과태료) 사전통지서_오지안.pdf',
        filePath: 'C:\\notice-generator\\samples\\pre_notice_oh_jian.pdf',
      },
      {
        id: 'suspension',
        title: '운전업무정지',
        fileName: '행정처분(운전업무정지) 사전통지서_오지안.pdf',
        filePath: null,
      },
      {
        id: 'final-notice',
        title: '확정통지서',
        fileName: '행정처분 확정통지서_오지안.pdf',
        filePath: null,
      },
    ],
  },
]

export const payerStatusMeta = {
  advance: {
    label: '사전납부',
    badgeClass: 'bg-sky-50 text-sky-700 ring-1 ring-inset ring-sky-200',
    toneClass: 'bg-sky-50',
  },
  confirmed: {
    label: '확정납부',
    badgeClass: 'bg-amber-50 text-amber-700 ring-1 ring-inset ring-amber-200',
    toneClass: 'bg-amber-50',
  },
} as const

export const payerPaymentStatusMeta = {
  unpaid: {
    label: '미납',
    badgeClass: 'bg-rose-50 text-rose-700 ring-1 ring-inset ring-rose-200',
  },
  paid: {
    label: '납부완료',
    badgeClass: 'bg-emerald-50 text-emerald-700 ring-1 ring-inset ring-emerald-200',
  },
} as const

export const formatPayerCurrency = (value: number) => `${value.toLocaleString('ko-KR')}원`
